### ISSUE TITLE
Ionic Pro build failed

### ISSUE THREAD

**Issue by goverdhanpaliwal** [arnesson/cordova-plugin-firebase#840] opened 2018-09-11 09:05 UTC
**Plugin with id 'com.google.gms.google-services' not found.**
we can't change manually in  build.gradle file.

`The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_dczd6dp0q9phbzjp0lgrh3ndj.run(/usr/src/app/platforms/android/build.gradle:150)
File /home/gitlab-runner/.android/repositories.cfg could not be loaded.
Checking the license for package Android SDK Platform 26 in /opt/android-sdk/licenses
License for package Android SDK Platform 26 accepted.
Preparing "Install Android SDK Platform 26 (revision: 2)".
"Install Android SDK Platform 26 (revision: 2)" ready.
Installing Android SDK Platform 26 in /opt/android-sdk/platforms/android-26
"Install Android SDK Platform 26 (revision: 2)" complete.
"Install Android SDK Platform 26 (revision: 2)" finished.

FAILURE: Build failed with an exception.

* Where:
Script '/usr/src/app/platforms/android/cordova-plugin-firebase/test-build.gradle' line: 27

* What went wrong:
A problem occurred evaluating root project 'android'.
> Plugin with id 'com.google.gms.google-services' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 14s
(node:1) UnhandledPromiseRejectionWarning: Error: /usr/src/app/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script '/usr/src/app/platforms/android/cordova-plugin-firebase/test-build.gradle' line: 27

* What went wrong:
A problem occurred evaluating root project 'android'.
> Plugin with id 'com.google.gms.google-services' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 14s
    at ChildProcess.whenDone (/usr/src/app/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by juanjgarcia** [comment] 2018-09-11 12:13
I think this may be solved by the `cordova-android-support-gradle-release` package

**Comment by jpduckwo** [comment] 2018-09-11 12:28
@juanjgarcia Thanks for the suggestion, didn't work for me though.

**Comment by briantq** [comment] 2018-09-11 16:19
Duplicate of Issue #837

**Closed by briantq** 2018-09-11 16:19 UTC
