### ISSUE TITLE
Notifications never arrive when app is closed or in background.

### ISSUE THREAD

**Issue by adolfobushi** [arnesson/cordova-plugin-firebase#711] opened 2018-05-28 00:23 UTC
I installed the last stable version of the plugin and also installed from github. The version of cordova android is 7.0.
The problem is that the notifications arrive correctly if the app is in foreground, but never arrive when the app is in background. 
If the app is completelly closed the app is opened.

**Comment by diegodambra** [comment] 2018-05-28 13:53
Seems similar to what I'm experiencing, see [https://github.com/arnesson/cordova-plugin-firebase/issues/568#issuecomment-392522142](#568).

With "never arrive when in background" do you mean that no message is displayed in the device notification bar?

Try if you app is getting the notification while in the background, window.FirebasePlugin.onNotificationOpen is trigged regardless of app being paused or not. If that is the case then we're seeing same problem, sorry...

**Comment by adolfobushi** [comment] 2018-05-28 14:33
Hello @diegodambra, yes it is the same problem. I have android 6 in my phone. The plugin is the last version 1.0.5.

**Comment by diegodambra** [comment] 2018-06-04 11:57
@adolfobushi Tried plugin cordova-plugin-fcm and same issue. Root cause must be something else.

Now it's working, but I don't know why. Tried multiple times to delete plugins/platforms and add them again without success, pulled a previous version of my code and volá!

**Comment by tyagoy** [comment] 2018-06-15 14:15
@diegodambra so when using an old version of plugin it worked. What was the version?

**Comment by diegodambra** [comment] 2018-06-18 10:15
@tyagoy not an older version of the firebase plugin, it has always been 1.0.5.

And the firebase plugin continues to work. I've made several changes and updates to my project  - zero problems! When app is in background, push notifications are received as expected.

**Comment by soumak77** [comment] 2018-08-30 02:46
closing as resolved

**Closed by soumak77** 2018-08-30 02:46 UTC
