### ISSUE TITLE
Push notification received twice on android

### ISSUE THREAD

**Issue by corentinbaur** [arnesson/cordova-plugin-firebase#75] opened 2016-10-19 15:34 UTC
With this code in my cordova app, when I send a push since firebase, my app receive 2 notifications instead of 1.

``` js
var firebasePlugin = window.FirebasePlugin;

firebasePlugin.getInstanceId(function(token) {
       console.log(token);
   }, function(error) {
       console.log(error);
   });

   firebasePlugin.onNotificationOpen(function(notification) {
       console.log(notification);
   }, function(error) {
        console.log(error);
   });
```

Is missing something in my code ?
Thanks

**Comment by zgluis** [comment] 2016-10-20 15:47
Hello, I'm having the same problem,more specifically the onNotificationOpen is executing twice, Log:

> onNotificationOpen file.js:23 
> Object {} file.js:24 
> onNotificationOpen file.js:23 
> Object {}controllers.js:24

I also would like to know how to get the notification's content(title,message)? I can't find anything in that Object{}

**Comment by namuit** [comment] 2016-10-21 17:08
in Android I have the same problem. In iOS the behaviour is correct

**Comment by o969152964** [comment] 2016-10-23 02:59
Same problem twice on android

**Comment by ZameelAmjed** [comment] 2016-10-26 11:33
same issue in android. onNotificationOpen() is called twice on foreground 
```
window.FirebasePlugin.onNotificationOpen(function (notification) {
                try{
                  console.log(notification);
                    var item = angular.toJson(notification);
                    $ionicPopup.alert({
                        title: item.title,
                        template: item.text
                    });
                }catch (e){
                    alert(e);
                }
}, function (error) {
         console.error(error);
});
```

**Comment by ZameelAmjed** [comment] 2016-10-28 05:13
i have put a comment on below two lines in OnReceive method  in OnNotificationOpenReciver.java and now seems the issue is sorted.  
```
//launchIntent.putExtras(data);
 //context.startActivity(launchIntent);
```

**Comment by robertarnesson** [comment] 2016-11-01 19:11
fixed in 437b228c1e19518e6ec83f1c24326c04fb80adc4

**Closed** 2016-11-01 23:03 UTC

**Comment by corentinbaur** [comment] 2016-11-08 14:27
I think that we don't have the same problem.
When I send a notification from firebase console or with http api, I receive the same notification twice.

Someone have the same problem ?

![android_notif](https://cloud.githubusercontent.com/assets/6905759/20102645/1e05be1e-a5c7-11e6-9639-eafcdf6e2a12.png)

**Comment by JumBay** [comment] 2017-02-01 12:37
Had the same issue on Android: 
- 1 notification if the app is in foreground
- 2 notifications if the app is in background 

No issue on iOS

**Comment by JumBay** [comment] 2017-02-01 13:14
Actually this happens because I'm using this plugin https://github.com/intercom/intercom-cordova. If I remove it, the notification shows once
