### ISSUE TITLE
Android Background Notification not show

### ISSUE THREAD

**Issue by psmump** [arnesson/cordova-plugin-firebase#72] opened 2016-10-12 19:14 UTC
When the apps clear from task.i try to send the push notification from the console ,but it will not received in background process.It success in foreground but failed in background apps for android..please help :( any suggestion ?

**Comment by neolectron** [comment] 2016-10-17 03:16
for me its the opposite, with the app in background or foreground, its always the push-notification that shows-up.

**Comment by ramzed** [comment] 2016-10-18 12:53
I have the same issue.
When my app in foreground I get push notification correctly.
In logcat I see:
`I/MediaCodec(  377): [onMessageReceived]line:1312 [][what=kWhatInit][state 0][msg='AMessage(what = 'init', target = 2052) = {
I/MediaCodec(  377): [onMessageReceived]line:954 [][what=kWhatComponentAllocated][state 1][msg='AMessage(what = 'codc', target = 2052) = {
I/MediaCodec(  377): [onMessageReceived]line:982 [OMX.google.vorbis.decoder][what=kWhatComponentConfigured][state 3][msg='AMessage(what = 'codc', target = 2052) = {
I/MediaCodec(  377): [onMessageReceived]line:1039 [OMX.google.vorbis.decoder][what=kWhatBuffersAllocated][state 5][msg='AMessage(what = 'codc', target = 2052) = {
I/MediaCodec(  377): [onMessageReceived]line:1039 [OMX.google.vorbis.decoder][what=kWhatBuffersAllocated][state 5][msg='AMessage(what = 'codc', target = 2052) = {
I/MediaCodec(  377): [onMessageReceived]line:1039 [OMX.google.vorbis.decoder][what=kWhatBuffersAllocated][state 6][msg='AMessage(what = 'codc', target = 2052) = {
I/MediaCodec(  377): [onMessageReceived]line:1252 [OMX.google.vorbis.decoder][what=kWhatEOS][state 6]`

But when my app in background or was swipped out (manually killed), I don't get any messages in logcat.

Android 5.1 Meizu M3 note. Flyme 5.1.3.2G

Should I request any permissions?

Thank you in advance!

**Comment by ramzed** [comment] 2016-10-18 13:12
I think I understand.
I tried send push notifications from Firebase GUI. It generates only display-messages. These type of messages trigger the onMessageReceived() callback only when app is in foreground.
There is another type which is called data-messages. These messages trigger the onMessageReceived() callback even if your app is in background. I try to send data message and will give my feedback.

**Comment by ZameelAmjed** [comment] 2016-11-03 08:35
I think the issue is now sorted in latest push..you may close this

**Closed** 2016-11-04 14:06 UTC
