### ISSUE TITLE
 Error: Found item String/google_app_id more than one time

### ISSUE THREAD

**Issue by zerdos** [arnesson/cordova-plugin-firebase#407] opened 2017-08-25 16:15 UTC
Breaking change in the new tag: "cordova-plugin-firebase": "^0.1.24",

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeReleaseResources'.
> /Users/zoltan/Developer/myProject/platforms/android/res/values/strings.xml: Error: Found item String/google_app_id more than one time

The content of strings.xml:
```
<?xml version='1.0' encoding='utf-8'?>
<resources>
    <string name="app_name">My app name</string>
    <string name="launcher_name">@string/app_name</string>
    <string name="activity_name">@string/launcher_name</string>
    <string name="google_app_id">xxxxxxx---xxxxxxx</string>
    <string name="google_api_key">xxxxxxx---xxxxxxx</string>
    <string name="google_app_id">@string/google_app_id</string>
    <string name="google_api_key">@string/google_api_key</string>
</resources>
```

**Comment by robertarnesson** [comment] 2017-08-25 16:55
you probably have another plugin that is also adding google_app_id and google_api_key

**Comment by falcon8823** [comment] 2017-08-28 03:36
I faced same problem too in 0.1.24. And this problem occurs only release build.
I don't have another plugin that is also adding google_app_id and google_api_key.

**Comment by zerdos** [comment] 2017-08-28 08:45
To reproduce the issue:

1. delete the plugins, and platform folder
2. add the platform android
3. add the platform ios
4. try to build the android version

The problem is, that if the ios platform added, then the after_prepare file runs again.
Also it tries:
```if (directoryExists(IOS_DIR)) {
    copyKey(PLATFORM.IOS);
} else if (directoryExists(ANDROID_DIR)) {
    copyKey(PLATFORM.ANDROID, updateStringsXml)
}
```

So the  copyKey(PLATFORM.ANDROID, updateStringsXml) runs,
it copies the keys, then in the function exception happens, so the callback function won't be called.

**Comment by akaushik79** [comment] 2017-08-30 16:24
Anyone found the solution of this problem. I tried removing few lines from plugin.xml after which build was successful but i saw below error in logs:
GoogleService failed to initialize, status: 10, Missing google app id value from from string resources with name google_app_id.

**Comment by inidona** [comment] 2017-08-30 19:44
hi, i also have this issue, the version 0.1.22 is the last working for me

**Comment by pvdyck** [comment] 2017-09-05 16:33
@zerdos confirmed, good analysis.

I was doing cordova platform add android before cordova platform add ios ... now it works.

**Comment by Mehuge** [comment] 2017-09-13 10:47
I get this problem every time I do `cordova build android`, it re-adds the google_app_id / key to res/values/strings.xml every time, and so the build fails.

**Comment by dleric** [comment] 2017-09-15 07:45
@inidona downgrading to 0.1.22 also worked for me.

**Comment by fbrun** [comment] 2017-10-04 10:14
I get the same problem. However, I notice that the content of actual after_prepare is newer than the version of the npm package, though the script was merged in the same date of version ?

**Comment by igorPhelype** [comment] 2017-10-18 12:34
`$ cordova clean android` worked here

**Comment by Mehuge** [comment] 2017-10-18 15:38
The problem I believe is this in the config:-

    <config-file parent="/resources" target="res/values/strings.xml">
        <string name="google_app_id">@string/google_app_id</string>
    </config-file>
    <config-file parent="/resources" target="res/values/strings.xml">
        <string name="google_api_key">@string/google_api_key</string>
    </config-file>

Not sure what that is attempting to achieve but I changed mine to 

    <preference name="API_KEY"/>
    <preference name="APP_ID"/>

    <config-file parent="/resources" target="res/values/strings.xml">
        <string name="google_app_id">$APP_ID</string>
        <string name="google_api_key">$API_KEY</string>
    </config-file>

and I install the plugin by adding

   cordova plugin add ../plugins/my-firebase-plugin --variable APP_ID=<my-app-id> --variable API_KEY=<my-api-key>

and it works fine now.

**Comment by rabinski99** [comment] 2017-10-20 03:16
I made a change to the` cordova-plugin-firebase/scripts/after_prepare.js` so that both ios and android get copied if they both exist.

```
if (directoryExists(IOS_DIR)) {
    copyKey(PLATFORM.IOS);
}

if (directoryExists(ANDROID_DIR)) {
    copyKey(PLATFORM.ANDROID, updateStringsXml);
}
```

**Comment by zstergios** [comment] 2017-10-23 14:42
Same issue! Any solution?
Firstly I copy the google-services.js after that I add the plugin via cli and and i build it. and I got the above error....

@rabinski99 this a very good suggestion!

**Comment by stephdgenius** [comment] 2017-11-03 14:58
Remove this in strings.xml
```
<string name="google_app_id">Your API ID</string>
<string name="google_api_key">Your API KEY</string>
<string name="google_app_id">@string/google_app_id</string>
<string name="google_api_key">@string/google_api_key</string>
```
**Work for me**

**Comment by harishmahajan** [comment] 2017-11-24 06:52
@stephdgenius @pamelita04 
i removed it, but now i am getting this error.
Error: Cannot set property 'text' of null

**Comment by petemcwilliams** [comment] 2017-11-29 12:05
Updating strings.xml or any file created during the build is not a solution it is a workaround of an issue.  We need reliable repeatable builds without manually having to update files.

**Comment by Mehuge** [comment] 2017-11-29 12:23
#issuecomment-337633326

Is reliable, and repeatable and doesn't require manually updating files.

**Comment by vijeth-ag** [comment] 2018-01-04 06:09
I removed and re-added android platform, the error( Found item String/google_app_id more than one time) disappeared.
> cordova platform rm android
> cordova platform add android

**Comment by jacquesdev** [comment] 2018-02-07 11:54
I am experiencing this same issue with 0.1.25, any chance it will be fixed anytime soon?

**Comment by jacquesdev** [comment] 2018-02-07 14:09
I think I have found the cause of the issue, please see this issue https://github.com/phonegap/phonegap-plugin-push/issues/1660.

Essentially it happens if you are using version < 2.0 of the phonegap-plugin-push cordova plugin, so obviously there is going to be a conflict whatever version of this plugin is used (I tried with 0.1.22, but even that did not work).

**Comment by robertarnesson** [comment] 2018-02-27 11:12
closing for now, reopen if still an issue with the latest version of the plugin

**Closed by robertarnesson** 2018-02-27 11:12 UTC

**Comment by Dileep124** [comment] 2018-08-28 18:42
hi there,
kindly help me please  resultTextview always error why?
 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Button addBtn = (Button) findViewById(R.id.addBtn);
        addBtn.setOnClickListener(new View.OnClickListener()){
            @Override
            public void OnClick(View View){
                EditText FirstNumEditText = (EditText) findViewById(R.id.firstNumEditText);
                EditText SecondNumEditText = (EditText) findViewById(R.id.secoundNumEditText);
                TextView Result = (TextView)findViewById(R.id.resultTextview);

                int num1 = Integer.parseInt(FirstNumEditText.getText() .toString());
                Resources secoundNumEditText;
                int num2 = Integer.parseInt(secoundNumEditText.getText() .toString());
                int result = num1 + num2;
                int result = num1 / num2;
                int result = num1 * num2;
                resultTextview.SetText{result + "");

**Comment by Dileep124** [comment] 2018-08-28 18:47
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Button addBtn = (Button) findViewById(R.id.addBtn);
        addBtn.setOnClickListener(new View.OnClickListener()){
            @Override
            public void OnClick(View View){
                EditText FirstNumEditText = (EditText) findViewById(R.id.firstNumEditText);
                EditText SecondNumEditText = (EditText) findViewById(R.id.secoundNumEditText);
                TextView Result = (TextView)findViewById(R.id.resultTextview);

                int num1 = Integer.parseInt(FirstNumEditText.getText() .toString());
                Resources secoundNumEditText;
                int num2 = Integer.parseInt(secoundNumEditText.getText() .toString());
                int result = num1 + num2;
                int result = num1 / num2;
                int result = num1 * num2;
                resultTextview.SetText{result + "");

erro the resultTextView here i don't no reson why?
