### ISSUE TITLE
[Android] Notification callback won't be fired after receiving a notification in background

### ISSUE THREAD

**Issue by chanphillip** [arnesson/cordova-plugin-firebase#86] opened 2016-11-02 06:23 UTC
I just updated to 0.1.18. Here are the situation:

1) Notification callback has been fired properly when the app is in foreground, no matter how many notifications are received.
2) Jumping to background and then foreground, it still fires the callback when receiving notifications.
3) Once the app becomes in background and received a notification which is showing in tray, opening the app and the callback won't be fired again anymore.

I'm not sure if this is the same issue as some open issues regarding notifications on Android.

**Comment by feruzm** [comment] 2016-11-02 12:08
Anyone found solution for Android?

**Comment by blckshrk** [comment] 2016-11-09 13:08
Same problem here. I need a fix for a production app. Is there a version who works correctly ?

**Comment by ManuelOverdijk** [comment] 2016-11-10 10:53
I'm not sure if it's related, but when using cordova-plugin-crosswalk-webview (2.1.0, crosswalk version 21+), no native events are received at all. Installing this version:  cordova plugin add https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview#f6d1ef308 --save fixes the problem for me (See https://issues.apache.org/jira/browse/CB-12113). My onNotificationOpen callback triggers on android in the foreground (Android 7.0). I hope this might help.

**Comment by chanphillip** [comment] 2016-11-12 09:09
I think I've solved the problem!
I just simply add calling onNotificationOpen when onResume, and then it works perfectly.

I'm using ionic 2 framework. I handle onResume by:
> this.platform.resume.subscribe(...)

**Comment by Abichai** [comment] 2016-11-21 11:59
For Android, the issue is coming from the notification callback context being a WeakReference thus when the app is in background the garbage collector erase the callback context which make impossible to send notification to the javascript. I change the notification callback context to just being a Callback Context Object now I'm not having the issue.

**Comment by feruzm** [comment] 2016-11-21 12:01
@Abichai Do you have sample of code?

**Comment by Abichai** [comment] 2016-11-21 12:10
@feruzm I just changed the FirebasePlugin.java on line 48
`private static WeakReference<CallbackContext> notificationCallbackContext;` by `private static CallbackContext notificationCallbackContext;`

and make the change to respect this new  change:
line 143: `FirebasePlugin.notificationCallbackContext = new WeakReference<CallbackContext>(callbackContext);` become `FirebasePlugin.notificationCallbackContext = callbackContext;`

line 178 `final CallbackContext callbackContext = FirebasePlugin.notificationCallbackContext.get();` to `final CallbackContext callbackContext = FirebasePlugin.notificationCallbackContext;`

line 215 get rid of this condition `FirebasePlugin.notificationCallbackContext.get() != null;`

**Comment by feruzm** [comment] 2016-11-22 12:30
@Abichai changes didn't help

**Comment by feruzm** [comment] 2016-11-22 15:15
OnNotificationOpenReceiver.java never gets to call or doesn't revoke app when it is in background and notification is arrived. Callback on notification tap should call that file OnReceive function I suppose, I have few logs, it never fires...

**Comment by device68** [comment] 2017-01-18 19:37
On Android you MUST use Resume to capture onNotificationOpen after an app has been opened, placed in the background, then opened again. I have discussed this at length with video demo here #108

**Comment by robertarnesson** [comment] 2017-05-04 12:31
closing this as it is a duplicate of #108

**Closed by robertarnesson** 2017-05-04 12:31 UTC
