### ISSUE TITLE
PLUGIN_NOT_INSTALLED (verifyPhoneNumber - ANDROID)

### ISSUE THREAD

**Issue by leoassiscosta** [arnesson/cordova-plugin-firebase#647] opened 2018-04-18 19:09 UTC
Steps:
npm install -g ionic cordova
npm install firebase angularfire2 --save
ionic start authApp blank
ionic cordova platform add android
ionic cordova plugin add cordova-plugin-firebase
npm install --save ionic-native/firebase
Copy google-services.json

ionic cordova buld android --release
Assign the App
Register app in firebase.
Install app in android device

When i execute verifyPhoneNumber function show me a error in device
PLUGIN_NOT_INSTALLED
Exception java.lang.Exception: plugin_not_installed
org.apache.cordova.firebase.FirebasePlugin$13.run (FirebasePlugin.java:445)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)

PS: in same button i invoke getToken(), and returns normally

public sendPhone(phoneNumber: number){
try{
this.firebase.getToken().then(token => this.toast.show(The token is ${token}));
this.firebase.verifyPhoneNumber("+5551993431088",5000).then(value =>{
        this.toast.show(value);
      })
      .catch((error) => {
        this.toast.show(error);
        this.firebase.logError(error);
        //console.error("SMS não enviado", error);
      });
}
catch(error)
{
this.toast.show(error.message);
}
}

**Comment by webgear88** [comment] 2018-04-19 07:46
i have the same issue , keep asking to install but i already installed
[15:38:39]  console.warn: Native: tried calling Firebase.verifyPhoneNumber, but the Firebase plugin is not installed.
[15:38:39]  console.warn: Install the Firebase plugin: 'ionic cordova plugin add cordova-plugin-firebase'

**Comment by dramentol** [comment] 2018-04-24 14:33
Can you please run _ionic info_ command and post the output?

**Comment by leoassiscosta** [comment] 2018-04-24 19:30
cli packages: (C:\Users\Leandro\finalTest\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.11.1
    npm  : 5.7.1
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy

**Comment by webgear88** [comment] 2018-04-25 05:59
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v9.11.1
    npm               : 6.0.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.3 Build version 9E145

Environment Variables:

    ANDROID_HOME : /Users/andyng/Library/Android/sdk

Misc:

    backend : pro

**Comment by nicolasmoreira** [comment] 2018-04-26 01:10
@webgear88 I think that the issue is fixed, try to install this plugin from git instead

**Comment by soumak77** [comment] 2018-04-26 02:40
should be fixed by version 1.0.2

**Closed by soumak77** 2018-04-26 02:40 UTC

**Comment by webgear88** [comment] 2018-04-26 03:35
Tested on iOS and Android .. it's works. thank you

**Comment by Jaylton** [comment] 2018-08-21 00:04
Can you solve this?
