### ISSUE TITLE
Expand and Contract Messages in the android notification drawer

### ISSUE THREAD

**Issue by iamntg** [arnesson/cordova-plugin-firebase#104] opened 2016-11-22 12:24 UTC
Hi,

Thank you very much for the plugin.
Is there any ways to Expand and Contract the notification messages in the android notification drawer?.

please check the example:
![notifications_guidelines6](https://cloud.githubusercontent.com/assets/19806010/20523767/a43e9cc4-b0dc-11e6-8697-e5c5b8ab3e57.png)

**Comment by robertarnesson** [comment] 2018-02-27 10:56
duplicate of #105

**Closed by robertarnesson** 2018-02-27 10:56 UTC
