### ISSUE TITLE
Ionic App freezes on launch after notification received on iOS

### ISSUE THREAD

**Issue by rlegallais** [arnesson/cordova-plugin-firebase#811] opened 2018-08-30 09:02 UTC
@cordova 8.0.0
@cordova-ios 4.5.4

Hi,
I have a problem on iOS on my ionic (v1) application when I receive a notification and the application is closed. The small "1" badge is well-displayed on the icon. But when I click on the notification (or when I open the app simply by clicking on the app icon), randomly the apps freezes on the splash screen. The problem is that sometimes the app opens well and sometimes it freezes and I haven't identified the reason. 

On top of that I haven't manage to catch error messages so far in the console. Every time I try to catch this bug, actually the app opens well... 

I thought that maybe the Firebase plugin was not loaded, so I put lots of safety measures and "if" statements in my code but it stills freezes. 

This is an extract of my code on notifications management in my main controller : 

```
var firebase_ready = function() { 
   if(typeof cordova != "undefined" && cordova && typeof window.FirebasePlugin != "undefined" && window.FirebasePlugin) { 
         try { 
             var saveToken = function(token) {  // Save token 
                   if(token !== null && token !== ''){ 
                       window.localStorage.setItem('firebase_token',token);
                       onNotificationOpen(); 
                    } 
               }; 

            var errorToken = function(err) {   // Error token
                console.log('error retrieving firebase token: ' + err); 
            }; 

           var manageToken = function(success) { 
                 if(success) { 
                       window.FirebasePlugin.getToken(saveToken, errorToken); 
                       window.FirebasePlugin.onTokenRefresh(saveToken, errorToken); 
                 } 
           }; 

          var onNotificationOpen = function() { 
                window.FirebasePlugin.onNotificationOpen(function(data){ 
                     //Notification received on device tray and tapped by the user. [In background] 
                     if(typeof data != "undefined" && data && data.tap){ 
                          console.log('Notification BG'); 
                     } else if(typeof data != "undefined" && data){ // App in foreground
                               console.log('Notification FG'); 
                               if(typeof data.aps != "undefined" && data.aps && data.aps.badge) { 
                                    var badgeNum = angular.isNumber(data.aps.badge) ? parseInt(data.aps.badge) : 0; 
                                     window.FirebasePlugin.setBadgeNumber(badgeNum); 
                               } else if(typeof data.notification != "undefined" && data.notification && data.notification.badge) {
                                    var badgeNum = angular.isNumber(data.notification.badge) ? parseInt(data.notification.badge) : 0; 
                                    window.FirebasePlugin.setBadgeNumber(badgeNum); 
                             } 
                      } 
                }, function(msg){  console.log('onNotification callback successfully registered: ' + msg);  }, 
                    function(err){  console.log('Error registering onNotification callback: ' + err); } 
               ); 
           }; 

      if($ionicPlatform.is('ios')) { 
          window.FirebasePlugin.hasPermission(function(data){ 
               if(!data.isEnabled) { 
                   window.FirebasePlugin.grantPermission(manageToken, errorToken); 
                } else { 
                   manageToken(true); 
                } 
           }); 
       } 
    } catch(e) { console.log('Error firebase: ' + e); } 
  } 
}; 

$ionicPlatform.ready(function() { 
    $timeout(function() { // I tried with a timeout here without any success
        firebase_ready(); 
     },200); 
});
```

Do you know what happends ? And why it is random ?
Thanks

**Comment by briantq** [comment] 2018-09-11 15:50
What version of the plug-in are you running. You can tell by running cordova plugins list

**Comment by svzi** [comment] 2018-09-17 10:48
I'm having the same issue with my Ionic 3 app. I'm using

```
cordova-plugin-firebase 1.0.5 "Google Firebase Plugin"
```

Does someone have an idea? It only happens on iOS and, as far as I know, when a badge is set. Any help would be really much appreciated!

**Comment by briantq** [comment] 2018-09-17 15:14
@svzi I have not seen that.  I would try to add some logging into your JS code to see if it is loading.  Something like a "hello world" in the onLoad event in your HTML.  That should help you figure out where in the stack it is freezing.  You can also put break points in the .m classes of the native code to try to trace the execution of native code.

**Comment by svzi** [comment] 2018-09-20 19:14
@briantq Thanks for your feedback, appreciate that. Unfortunately, not all iOS devices are affected. I don't have that issue on my own devices, but I recently got a bunch of mails from customers, as well as one star ratings, because of this issue. This really sucks and it's really hard to debug or understand, if you can't reproduce. So I can't even use breakpoints or make console outputs... Any other ideas?

**Comment by rlegallais** [comment] 2018-10-08 09:28
@briantq 
Here is the list of my plugins :

branch-cordova-sdk 3.0.0 "branch-cordova-sdk"
card.io.cordova.mobilesdk 2.1.0 "CardIO"
com-badrit-base64 0.2.0 "Base64"
com.verso.cordova.clipboard 0.1.0 "Clipboard"
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-badge 0.7.3 "Badges"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 2.2.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebase 1.0.5 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-ignore-lint-translation 0.0.1 "cordova-plugin-ignore-lint-translation"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-mixpanel 4.3.0 "Mixpanel"
cordova-plugin-nativestorage 2.2.2 "NativeStorage"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.6 "Cordova WKWebView Engine"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-plugin-x-toast 2.6.0 "Toast"
cordova-sqlite-storage 2.3.3 "Cordova sqlite storage plugin"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
me.tonny.cordova.plugins.multidex 0.1.0 "Cordova Multi Dex"

The issue here is really the randomness of the freeze that seems to happen at launch.

**Comment by briantq** [comment] 2018-10-08 14:57
I see a number of people are using the 1.0.5 version of the plug-in. That version has been out for almost 6 months and I have personally used it for a number of weeks before upgrading to 2.X (I'm late to the Cordova party). 

Since there are only a handful of issues it leads me to think it's a configuration/environmental issue. 

Since we can't access everyone's code base I believe the best way to proceed is to put a break point in the .M native code to trace and make sure it's firing correctly and not getting hung.

You might also check to see if there are any Firebase bugs that mention similar behavior. It could be a FB issue.

 Sorry I can't be more help.

**Comment by soumak77** [comment] 2018-10-10 05:53
This should be fixed with the latest version.  Please reopen if it is not.

**Comment by rlegallais** [comment] 2018-10-19 10:28
I just experienced the issue with the latest version of the plugin 2.0.5. 
I received a notification, I opened this app and it froze on the splash screen, whereas one hour before, I received a notification, opened the app and no problem.

**Comment by svzi** [comment] 2018-10-19 10:58
@soumak77 Sadly I'm experiencing the same issue like @rlegallais ! I've updated the plugin to 2.0.5 and hoped everything would finally work as expected, but the new version doesn't look to fix the issue. At least not completely, maybe it doesn't happen that often, but I doubt that anything has changed. At least in my project. :(

**Comment by svzi** [comment] 2018-10-20 12:09
@soumak77 Please re-open this ticket, it's really important that this issue get fixed!

**Comment by briantq** [comment] 2018-10-22 20:40
@svzi @rlegallais I am reopening the issue since it does not appear to be fixed.  Please note that if a bug has no activity for a number of month, it will be closed due to inactivity.  I wish I could offer up more helpful information.

**Comment by svzi** [comment] 2018-10-22 20:46
@briantq Thanks for re-opening! I did two things in the last couple of days:

1. I've re-written all code regarding notification handling. Maybe I did something wrong initially, so I thought a completely new re-write could help. At least it couldn't get any worse on iOS! ;-)

2. I found out that maybe (!) this plugin doesn't need to be responsible for the freeze: https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/95 I implemented the necessary changes from that ticket as well. 

Yesterday my new beta was published on TestFlight. So far no iOS user had reported freezes, and there were already at least one push messages for each user. I will have to wait a few more days and let the finger crossed. Hopefully the issue is now solved. But if that would be the case, I wouldn't know if it was because of 1. or 2. or both...

**Comment by briantq** [comment] 2018-10-23 14:11
@svzi I'm crossing my fingers for you as I don't have any more ideas. Definitely let me know if it does resolve you issue and I can close the issue

**Comment by svzi** [comment] 2018-10-24 15:59
From my point of view, this ticket can be closed. It seems like my issue has been solved (see https://github.com/arnesson/cordova-plugin-firebase/issues/811#issuecomment-431978975). 👍

**Comment by briantq** [comment] 2018-10-25 13:44
@svzi I am really glad to hear you got it worked out!

**Closed by briantq** 2018-10-25 13:44 UTC
Labels: bug: runtime, component: messaging, help wanted, platform: iOS

**Comment by rlegallais** [comment] 2018-12-03 10:52
Sadly some users reported me they experienced this issue again. It is still random, sometimes the app is launching without any issue, sometimes it freezes, after a notification was received.

The answer above [#811](https://github.com/arnesson/cordova-plugin-firebase/issues/811#issuecomment-431978975) didn't apply to my app because I didn't have the cordova-plugin-ionic-webview plugin.

This is a list of my plugins :

branch-cordova-sdk 3.1.3 "branch-cordova-sdk"
card.io.cordova.mobilesdk 2.1.0 "CardIO"
com-badrit-base64 0.2.0 "Base64"
com.verso.cordova.clipboard 0.1.0 "Clipboard"
cordova-android-play-services-gradle-release 1.4.4 "cordova-android-play-services-gradle-release"
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-apprate 1.4.0 "AppRate"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-buildinfo 2.0.2 "BuildInfo"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 2.2.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-ignore-lint-translation 0.0.1 "cordova-plugin-ignore-lint-translation"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-mixpanel 4.3.0 "Mixpanel"
cordova-plugin-nativestorage 2.2.2 "NativeStorage"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.6 "Cordova WKWebView Engine"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-plugin-x-toast 2.6.0 "Toast"
cordova-sqlite-storage 2.3.3 "Cordova sqlite storage plugin"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
me.tonny.cordova.plugins.multidex 0.1.0 "Cordova Multi Dex"

**Comment by rlegallais** [comment] 2019-01-03 09:16
@soumak77 Please can you re-open this ticket, it's really important that this issue get fixed ?

**Comment by rlegallais** [comment] 2019-01-03 09:37
@svzi you're right, I'll do that !
In the meantime, could you share your current plugin list (as the issue is fixed for you) ? I'd like to compare our plugins list to identify the one that causes the freeze.

**Comment by svzi** [comment] 2019-01-03 09:45
Sure, here you are:

```
cc.fovea.cordova.purchase 7.1.3 "Purchase"
cordova-admob-plus 0.0.0 "@admob-plus/cordova"
cordova-clipboard 1.2.1 "Clipboard"
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-ios-plugin-no-export-compliance 0.0.5 "iOS No Export Compliance"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-apprate 1.4.0 "AppRate"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-cocoapod-support 1.6.0 "Cordova CocoaPods Dependency Support"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic 5.1.2 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.1 "SocialSharing"
cordova-plugin-x-toast 2.7.2 "Toast"
es6-promise-plugin 4.2.2 "Promise"
```

**Comment by rlegallais** [comment] 2019-01-03 11:43
Thanks @svzi 
Quick question, you said you implemented some changes to fix the issue based on this ticket https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/95.
Can you tell me which ones you have specifically implemented ?

**Comment by millerf** [comment] 2019-02-04 22:04
Experiencing the same problem on Android... I haven't tested on iOS yet...

Here is my list of plugins:
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.3.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.2 "Launch Navigator"

...

**Comment by millerf** [comment] 2019-02-04 22:18
@svzi Didn't do anything for me...

**Comment by svzi** [comment] 2019-02-04 22:31
@millerf Sorry, I never experienced this issue on Android.

**Comment by millerf** [comment] 2019-02-04 23:06
I am not sure as I need to investigate further, but it might be when reciving a notification from the background (`tap` is true ), I change the route of the angular router. Could that be the problem?

I'll test further...

**Comment by millerf** [comment] 2019-02-04 23:39
"Found" the bug. Using Ionic v4 NavController when receiving a notification freezes the app (at least on Android).
I just replaced the navCtrl.navigateRoot() with router.navigate()...

Thanks anyway! I will report to the ionic repo.
