### ISSUE TITLE
onNotificationOpen event doesn't fire once I tap on notification

### ISSUE THREAD

**Issue by Neustart** [arnesson/cordova-plugin-firebase#875] opened 2018-09-26 14:48 UTC
I am using latest version 2.0.2 and onNotificationOpen event doesn't fire once I tap on notification.
This happens on my Android device. Any idea how can I investigate this

**Comment by briantq** [comment] 2018-09-26 14:53
Duplicate of #865.  That issue has some suggestions on how to debug

**Closed by briantq** 2018-09-26 14:53 UTC
