### ISSUE TITLE
Build does not work for Android on Ionic 3

### ISSUE THREAD

**Issue by wilfredonoyola** [arnesson/cordova-plugin-firebase#763] opened 2018-07-05 22:35 UTC
Hi friends,

I have spent many time with this issue,

Please, Could you help me?

Thanks,

**ERROR INFO**
`FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find any version that matches com.google.android.gms:play-services-flags:12.+.
  Versions that do not match:
      15.0.1
      15.0.0
  Searched in the following locations:
      file:/Users/wilfredonoyola/Library/Android/sdk/extras/m2repository/com/google/android/gms/play-services-flags/maven-metadata.xml
      file:/Users/wilfredonoyola/Library/Android/sdk/extras/m2repository/com/google/android/gms/play-services-flags/
      file:/Users/wilfredonoyola/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-flags/maven-metadata.xml
      file:/Users/wilfredonoyola/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-flags/
      file:/Users/wilfredonoyola/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-flags/maven-metadata.xml
      file:/Users/wilfredonoyola/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-flags/
      https://jcenter.bintray.com/com/google/android/gms/play-services-flags/maven-metadata.xml
      https://jcenter.bintray.com/com/google/android/gms/play-services-flags/
      https://maven.google.com/com/google/android/gms/play-services-flags/maven-metadata.xml
      https://repo1.maven.org/maven2/com/google/android/gms/play-services-flags/maven-metadata.xml
      https://repo1.maven.org/maven2/com/google/android/gms/play-services-flags/
      file:/Users/wilfredonoyola/workspace/statusfy/sf-ionic-1/platforms/android/app/src/main/libs/
      file:/Users/wilfredonoyola/workspace/statusfy/sf-ionic-1/platforms/android/app/libs/
  Required by:
      project :app > com.google.firebase:firebase-crash:16.0.1
      project :app > com.google.firebase:firebase-auth:16.0.2
> Could not find any version that matches com.google.android.gms:play-services-measurement-base:12.+.`

**Ionic info:**
`cli packages: (/Users/wilfredonoyola/workspace/statusfy/sf-ionic-1/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v6.11.3
    npm               : 3.10.10 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4.1 Build version 9F2000 

Environment Variables:

    ANDROID_HOME : /Users/wilfredonoyola/Library/Android/sdk/

Misc:

    backend : pro`

**Comment by Flucadetena** [comment] 2018-07-31 14:55
The problem is with the ( com.google.android.gms:play-services-flags:12.+.) any library that you import must not have the "+"; you have to specify one specific version and ensure that there are no conflicts with other libraries.

For example, if you import:
com.google.android.gms:play-services-auth:11.0.4
com.google.android.gms:play-services-identity:11.0.4

They all must have the same version. If not you will get errors.

Some times you have to choose a lower version to achieve this, for example I use the 11.0.4 because greater ones gave me errors.

**Comment by Flucadetena** [comment] 2018-07-31 14:57
By the way, forgot to mention that you will have to change the version everywhere, so search for that library and change wherever the 12.+ version is called (in the plugin too), because if not, during the build it will be overwritten.

**Comment by wilfredonoyola** [comment] 2018-07-31 15:03
@Flucadetena Thanks for this advices,

I am going to try again and maybe I will come back here.

Thanks.

**Comment by Flucadetena** [comment] 2018-07-31 15:11
Ok if you get new errors tell me and if I can I will help. Many hours have gone down already with the Android errors jaajjaa

**Comment by wilfredonoyola** [comment] 2018-07-31 15:41
I am a little tired with Ionic 3, Because My project is down for this issues. But I hope to fix this.

**Comment by Flucadetena** [comment] 2018-07-31 15:44
I know them all in android. The first time to set it up is a pain. But after that everything is solve. Try and if you get new errors tell me and we will solve them. Don't worry ;)

**Comment by wilfredonoyola** [comment] 2018-07-31 15:47
Could you chat with me? Let me know

**Comment by Flucadetena** [comment] 2018-07-31 15:50
Yes, I have like 1h before i have to leave. Which service do you want to use?

**Comment by wilfredonoyola** [comment] 2018-07-31 15:51
Please add me on linkedin https://www.linkedin.com/in/wilfredo-noyola/

**Comment by okandeb** [comment] 2018-08-13 07:55
@wilfredonoyola Have you solved the problem?

**Comment by Flucadetena** [comment] 2018-08-13 09:09
Hi @okandeb, yes he did. Do you have any question? Haven't you been able to solve it with my explanation on top. Y you want, put here you android project properties and I'll tell you how to do it ;)

**Comment by okandeb** [comment] 2018-08-14 15:03
@Flucadetena thank you. i fixed it.

**Comment by soumak77** [comment] 2018-08-30 03:11
closing as resolved

**Closed by soumak77** 2018-08-30 03:11 UTC

**Comment by dimalahbal** [comment] 2018-09-28 21:07
what was your solution to solve the issue ??? please share it

**Comment by Gonzaloguib** [comment] 2018-09-28 21:40
Hi @dimalahbal. I can help you if you want. But I need to know your specific problem. I tell you the same as I said to okandeb :

"Hi @okandeb, yes he did. Do you have any question? Haven't you been able to solve it with my explanation on top. Y you want, put here you android project properties and I'll tell you how to do it ;) "

**Comment by okanseremet** [comment] 2018-09-30 16:04
when i encounter this problem i remove platform and add again and problem is solved. it occurs sometimes not often. thank you.
