### ISSUE TITLE
Plugin didnt use project root folder config file. PGB

### ISSUE THREAD

**Issue by maplerichie** [arnesson/cordova-plugin-firebase#39] opened 2016-08-25 07:47 UTC
Im using Phonegap build. Found that the plugin using src/<platform>/<plist/json> file instead of my project root folder
- My Project/
    platforms/
    plugins/
    www/
    config.xml
    google-services.json       <--
    GoogleService-Info.plist   <--
    ...
How to solve this issue?

**Comment by robertarnesson** [comment] 2016-08-25 14:34
duplicate of https://github.com/arnesson/cordova-plugin-firebase/issues/34

**Comment by maplerichie** [comment] 2016-08-26 16:04
I have go to #34 but there is no answer for me. Sorry, im still beginner to Cordova plugin, how should i implement after_prepare.js using Phonegap build?
Currently just have this line in my config.xml
<plugin name="cordova-plugin-firebase"/>

**Comment by robertarnesson** [comment] 2016-08-30 14:41
fixed in 806af2be91bb0bb448555af3aab3492b86244541

**Closed by robertarnesson** 2016-08-30 14:41 UTC
