### ISSUE TITLE
Unable to receive push notification on IOS

### ISSUE THREAD

**Issue by 05bca054** [arnesson/cordova-plugin-firebase#338] opened 2017-07-05 08:48 UTC
Hello,

Thanks for nice plugin.

But i have tried all the steps trice but still i can't get notification on my ionic app.

1. Crate push certificates.
2. Upload to firebase console. etc...

In firebase console it says sent successfully but unable to receive it on application side.

Using this tutorial for integration https://ionicframework.com/docs/native/firebase/

Please advise.

**Comment by soumak77** [comment] 2017-07-05 08:51
@05bca054 if you're using cordova v7, the latest release is broken for iOS.  I had to sync from master to get this plugin working.

**Comment by soumak77** [comment] 2017-07-05 08:57
Ignore my previous comment, I just noticed `0.1.22` was recently released

**Comment by 05bca054** [comment] 2017-07-06 17:31
@Soumak77 I tried both the version today but none of them work it gives error in console like.

**Failed to fetch APNS token Error Domain=com.firebase.iid Code=1001 "(null)"**

I think firebase faces problem to obtain APNS token somewhere

I have checked both(Dev & Prod) my p12 files working correctly for apns and same was uploaded to firebase ios app console.

**Comment by hoonblizz** [comment] 2017-07-31 15:26
I had the same issue. 
But believe or not, the issue is resolved once I turn off the notification and turn it on again.

**Comment by hoonblizz** [comment] 2017-08-01 13:51
Please ignore my previous comment. That method worked only for iOS9. In iOS 10, the same issue is still there.

**Comment by mathieu21** [comment] 2017-09-03 08:52
Same for me on iOS 10 no notifications received. Anyone found a fix for that ?

**Comment by damianobarbati** [comment] 2017-10-05 20:40
Same here, no notification received no the device but I correctly get a message_id from `fcm-push` server side.

**Comment by robertarnesson** [comment] 2018-02-27 11:19
closing for now, reopen if still an issue with the latest version of the plugin

**Closed by robertarnesson** 2018-02-27 11:19 UTC
