### ISSUE TITLE
[FirebasePlugin messaging:didRefreshRegistrationToken:]: unrecognized selector sent to instance 

### ISSUE THREAD

**Issue by fjckls** [arnesson/cordova-plugin-firebase#577] opened 2018-02-28 09:21 UTC
App crashes due to this error with the latest plugin release **0.1.25**

**Comment by kyleamadio** [comment] 2018-03-01 21:34
Confirmed this on IOS 11

[Firebase/Messaging][I-FCM002023] The object <FirebasePlugin: 0x1d409a770> does not respond to -messaging:didReceiveRegistrationToken:, nor -messaging:didRefreshRegistrationToken:. Please implement -messaging:didReceiveRegistrationToken: to be provided with an FCM token.

**Comment by kyleamadio** [comment] 2018-03-01 21:41
Bit more logging, tokens do get created and returned.

magicalCordovaIOS[2581:1042130] InstanceID token: f0hBo_SjJfQ:APA91bHUU7dZigBjzVtMeB-GvhLbX4avBWTru_gLOhzp6J5SYD9niTHAO47b-ZDWSGfF3829GMzpyJsT2KI58AWA6_9diVuGqj5tFfh6MfwI05KTSm6UprzW3yjIT47nEFzIPx0o3V3R

magicalCordovaIOS[2581:1042130] Unable to connect to FCM. Error Domain=com.google.fcm Code=2001 "FIRMessaging is already connected" UserInfo={NSLocalizedFailureReason=FIRMessaging is already connected}

magicalCordovaIOS[2581:1042130] Connected to FCM.

magicalCordovaIOS[2581:1042130] InstanceID token: f0hBo_SjJfQ:APA91bHUU7dZigBjzVtMeB-GvhLbX4avBWTru_gLOhzp6J5SYD9niTHAO47b-ZDWSGfF3829GMzpyJsT2KI58AWA6_9diVuGqj5tFfh6MfwI05KTSm6UprzW3yjIT47nEFzIPx0o3V3R

magicalCordovaIOS[2581:1042130] Asking for Firebase Permission
magicalCordovaIOS[2581:1042130] After asking for Firebase Permission

 magicalCordovaIOS[2581:1042810] [Firebase/Messaging][I-FCM002023] The object <FirebasePlugin: 0x1d409a770> does not respond to -messaging:didReceiveRegistrationToken:, nor -messaging:didRefreshRegistrationToken:. Please implement -messaging:didReceiveRegistrationToken: to be provided with an FCM token.

magicalCordovaIOS[2581:1042130] f0hBo_SjJfQ:APA91bHUU7dZigBjzVtMeB-GvhLbX4avBWTru_gLOhzp6J5SYD9niTHAO47b-ZDWSGfF3829GMzpyJsT2KI58AWA6_9diVuGqj5tFfh6MfwI05KTSm6UprzW3yjIT47nEFzIPx0o3V3R

magicalCordovaIOS[2581:1042130] Successfully Sent token to magical server... 

magicalCordovaIOS[2581:1042130] InstanceID token: etMUkNvSNgw:APA91bH43e9KMkUDrxSDs05kKWTlM1crSbRtDQqvazjWQNmI_b63UcvxWfKTcdvy4tuIio7osNZJsBGycrTmLSxXzobW5BhAcearjo-AlJ4D_BqoNrInXCMASAx0oV3-33KiOIRreG5l

magicalCordovaIOS[2581:1042130] Unable to connect to FCM. Error Domain=com.google.fcm Code=2001 "FIRMessaging is already connected" UserInfo={NSLocalizedFailureReason=FIRMessaging is already connected}

magicalCordovaIOS[2581:1042130] etMUkNvSNgw:APA91bH43e9KMkUDrxSDs05kKWTlM1crSbRtDQqvazjWQNmI_b63UcvxWfKTcdvy4tuIio7osNZJsBGycrTmLSxXzobW5BhAcearjo-AlJ4D_BqoNrInXCMASAx0oV3-33KiOIRreG5l

**Comment by kyleamadio** [comment] 2018-03-01 23:57
I think there may be a relationship with this error message:

FIRMessaging received **data-message**, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented.

The IOS 1.25 code does not accept Data Only notifications. Standard default Notifications are received successfully. Both with the app in the background and the foreground.

**Comment by kyleamadio** [comment] 2018-03-02 00:24
Here are the 3 message types:

**Data Only:**

[Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

**Notification Only:**

    aps =     {
        alert =         {
            body = "message body goes here";
            title = "Magical OI Example";
        };
    };
    "gcm.message_id" = "0:1519949841485656%98df36c898df36c8";
    tap = 0;
}

**Notification and Data:**

    aps =     {
        alert =         {
            body = "message body goes here";
            title = "Magical OI Example";
        };
    };
    "gcm.message_id" = "0:1519950025514507%98df36c898df36c8";
    icon = "https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/187591-L-LO.jpg";
    "original_item_id" = "%%MAGLIKEVIEWBC.LIKEGUIDS%%";
    tap = 0;
    text = "%%MAGLIKEVIEWBC.LIKENAMES%%";
    title = "%%ORYXSESSION.FIRSTNAME%% %%ORYXSESSION.LASTNAME%% added a new item";
    "to_name" = "%%MAGFRIENDLIKEBC.FRIENDFIRSTNAME%%";
    username = "%%ORYXSESSION.USERNAME%%";
}

**Comment by kyleamadio** [comment] 2018-03-02 03:25
If I did commented out this code in my Javascript, the Data message showed in the console

/*                
window.FirebasePlugin.grantPermission(function () {
                    window.FirebasePlugin.hasPermission(function (data) {
                        console.log(data.isEnabled);
                    });
                });
*/

**Comment by fjckls** [comment] 2018-03-02 07:02
Downgraded to 0.1.24 and that error went away - however IOS push notifications still not working in background nor foreground...

**Comment by kyleamadio** [comment] 2018-03-02 07:04
I’ll post my code and you can try it. It took a few days to figure it out. And a combination of other people’s code.

**Comment by fjckls** [comment] 2018-03-02 07:35
Thnks, nice one, I've been struggling with this for a while now. IOS push just doesn't work with Firebase, but on the other hand I can send notifications with APN directly using [https://github.com/noodlewerk/NWPusher](url)

**Comment by kyleamadio** [comment] 2018-03-02 10:14
Get the **latest cordova-plugin-firebase from GitHub**

cordova plugin add https://github.com/arnesson/cordova-plugin-firebase --save

In your  <appid>-Info.plist file, **FirebaseAppDelegateProxyEnabled = NO**

I assume you have set up the correct Firebase APNKEYs or ID's

**Check you <appname> Capabilities:**

![app capabilities](https://user-images.githubusercontent.com/1647986/36894087-789ab2ce-1e5e-11e8-9e9e-80771b9fd562.png)

I did not execute the grantPermission / hasPermission code - this stopped the Data notifications from working.

AppDelegate.m goes in <appname>/Classes and 

AppDelegate+FirebasePlugin.m goes in <appname>/Plugins/cordova-plugin-firebase


[AppDelegate.h.zip](https://github.com/arnesson/cordova-plugin-firebase/files/1774570/AppDelegate.h.zip)
[AppDelegate+FirebasePlugin.m.zip](https://github.com/arnesson/cordova-plugin-firebase/files/1774573/AppDelegate.FirebasePlugin.m.zip)

**Comment by kyleamadio** [comment] 2018-03-03 04:14
I have figured out that should only ask for permission first time app is installed and then thereafter just check via hasPermission:

                console.log('Checking for Notification Permission');

                            if (isIOS()) {
                    console.log('Checking for Notification Permission');
                    window.FirebasePlugin.hasPermission(function (data) {
                        if (!data.isEnabled) {
                            console.log("App does NOT have IOS Notification Permission");
                            magical.utility.popup('App cannot send you notifications via your device. Please go to settings \
                                    and enable app notifications');
                        } else {
                            console.log("App does have IOS Notification Permission " + data.isEnabled);
                        }
                    });
                }

**Comment by soumak77** [comment] 2018-03-06 09:54
Can anyone confirm whether https://github.com/arnesson/cordova-plugin-firebase/pull/576 fixes this issue?

**Comment by fjckls** [comment] 2018-03-06 10:23
I got working with this:
`cordova platform remove ios`
`cordova plugin add https://github.com/arnesson/cordova-plugin-firebase --save`
`cordova platform add ios`

**Comment by jonasmunk** [comment] 2018-03-14 08:37
This issue is blocking me from deploying an app.

I have limited Obj-C experience but it looks like at we at least need to stub the selector...
reason: '-[FirebasePlugin messaging:didRefreshRegistrationToken:]: unrecognized selector sent to instance 0x60000106c480'

Can someone point me to what delegate this method needs to be implemented in?

Does anyone know in what cases the problem may occur?

**Comment by fjckls** [comment] 2018-03-14 09:56
@jonasmunk Check what fixed it for me here  [#584](https://github.com/arnesson/cordova-plugin-firebase/issues/584#issuecomment-372600555)

**Comment by jonasmunk** [comment] 2018-03-14 10:00
@fjckls I do not believe that is a fix, if the delegate selector is not implemented the app will crash at seemingly random instances (very seldom).

Can you explain why this should fix the issue?

**Comment by fjckls** [comment] 2018-03-14 10:08
@jonasmunk to be honest haven't paid that much attention - that's just what I did - installed from git master instead of npm and there were no more errors, which where coming up constantly with the npm version...

**Comment by jonasmunk** [comment] 2018-03-14 10:10
@fjckls Ok, thanks - that sounds like a different issue then.

**Comment by jyk20000** [comment] 2018-04-10 15:31
@jonasmunk Did you find the solution? 
I got it rejected as well from iOS app store.

**Comment by soumak77** [comment] 2018-04-15 23:04
per @fjckls this has been fixed on master, so it should be resolved in version 1.0

**Closed by soumak77** 2018-04-15 23:04 UTC
