### ISSUE TITLE
Unable to update plugin on Cordova-Android 7.0.0! 

### ISSUE THREAD

**Issue by salouri** [arnesson/cordova-plugin-firebase#858] opened 2018-09-19 16:06 UTC
Cordova CLI 8.0.0
Cordova-Android 7.0.0
Current plugin version: 1.0.5

I was simply trying to remove the plugin to reinstall it again to update to version 2.0.0. But I am unable to do that and I get couple of errors on my way:

**First Error**: 

>  no such file or directory, open '.../platforms/android/AndroidManifest.xml'

**Workaround**: copied file AndroidManifest.xml from inside platforms/android/app/src/main to  /platforms/android/ ...and then I tried to remove it again. I got the second error

**Second Error**: 

> AndroidStudio.js:inAndroidStudioProject root does not exist: .../platforms/android

**Foundations:** from my search I found when this happens with other plugins people's conclusion is lack of support for Cordova-Android 7.0.0 and the solution is to downgrade to Android@6.4.0. (which is not an option in my case, too much headache).

What should I do now?

**Comment by briantq** [comment] 2018-09-19 17:13
Looks to be a duplicate of #849, as for some reason required platform files are going missing.  @salouri the work around in the other issue was to remove the Android platform, update/remove the plugin, then add the Android platform back.

**Closed by briantq** 2018-09-19 17:13 UTC

**Comment by salouri** [comment] 2018-09-20 13:14
even after removing android platform, removing firebase plugin, installing firebase again, adding android platform again....the following dependency configuration issues:  [1](https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/78), [2](https://stackoverflow.com/questions/27580249/crashlytics-error11-0-plugin-with-id-io-fabric-not-found-compile-lib) which I believe should be done automatically by the plugin.
Also it should be mentioned the removal of **google_api_key** and **google_app_id** from **platform/android/res/values/strings.xml** .

**Comment by briantq** [comment] 2018-09-20 14:13
@salouri Those issues should be resolved in the latest version of the plugin.  It no longer generates the keys for issue #1 that you mentioned.  Additionally, we modify the root build.gradle to allow the Crashlytics plugin to resolve #2.  

If you would like to submit documentation updates in a Pull Request we'd me more than happy to review it. There are no full time developers on the project so all updates are done through the effort that the community puts in.  Please see the Contribution Guidelines on how to create a Pull Request.
