### ISSUE TITLE
Blank white icon in notification bar

### ISSUE THREAD

**Issue by davejlong** [arnesson/cordova-plugin-firebase#321] opened 2017-06-19 20:43 UTC
I setup my project using the following in `colors.xml`:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <color name="primary">#FFFFFF00</color>
  <color name="primary_dark">#FF220022</color>
  <color name="accent">#FF20201e</color>
</resources>
```

And in `styles.xml`:

```
<?xml version="1.0" encoding="utf-8" ?>
<resources>
  <style name="AppTheme" parent="android:Theme.Light">
    <item name="android:windowDisablePreview">true</item>
  </style>
  <drawable name="notification_big">@mipmap/icon</drawable>
  <drawable name="notification_icon">@mipmap/icon</drawable>
</resources>
```

When the device receives a notification, in the notification bar is a white square for the icon. If I pull down the notification panel, I see the app icon with my access color background.

**Comment by rolinger** [comment] 2017-06-29 20:33
I don't believe these colors are working as intended...or icons for that matter.  I am passing color from the message itself:
```
  $fcmMsg = array(
    'body' => $msgBody,
    'title' => $msgTitle,
    'sound' => "default",
    'color' => "#cccccc",
    'icon' => "myappIcon.png"
  );
```
I have seen different response on different phones when changing color here from the server side script.  On Samsung Galaxy phones I see my actual app icon, and the background is the above color.  On LG K20 I see the outline of my app icon, but completely filled in with the above color.

Have you gotten it to work since you orig posted 10 days ago?

**Comment by soumak77** [comment] 2018-05-04 18:17
closing for cleanup

**Closed by soumak77** 2018-05-04 18:17 UTC
