### ISSUE TITLE
Add badge when receive notification

### ISSUE THREAD

**Issue by Kritsana-Punyaporn** [arnesson/cordova-plugin-firebase#627] opened 2018-03-30 03:18 UTC
I try to add badge number when receive message from server but it don't add badge number until I tapped on notification.

How to add badge number when device receive message? 
Help me please.

* I use setBadgeNumber and onNotificationOpen
************************ My code ************************
this.firebase.onNotificationOpen().subscribe((res) => {
        this.firebase.setBadgeNumber(1)
        if(res.tap){
          console.log("Received in background");
        } else {
          console.log("Received in foreground");
        }
      }, (err) => console.log(err) )

**Comment by remisture** [comment] 2018-04-02 14:59
Set badge number when you send the message.

**Comment by Kritsana-Punyaporn** [comment] 2018-04-03 07:14
@remisture Yes. I try to set badge number (badge = 1). I send it but if I receive message and do not open notification or application when I send message again badge number on my application still get 1

**Comment by soumak77** [comment] 2018-09-14 15:11
closing as duplicate of https://github.com/arnesson/cordova-plugin-firebase/issues/575

**Closed by soumak77** 2018-09-14 15:11 UTC
Labels: question
