### ISSUE TITLE
Problema no getToken()

### ISSUE THREAD

**Issue by jefvonmuhlen** [arnesson/cordova-plugin-firebase#613] opened 2018-03-22 21:46 UTC
Depois que atualizou para a versão 0.1.25 o meu aplicativo não pega mais o getToken, ele retorna sempre null. O que pode ser? Testei somente no Android por enquanto.

Meu código:

window.FirebasePlugin.hasPermission(function (data) {
                    if (data.isEnabled) {
                        window.FirebasePlugin.getToken(function(token) {
                            alert(token);
                        }, function(error) {
                            alert(error);
                        });
                    } else {
                        window.FirebasePlugin.grantPermission();
                    }
                });

**Comment by JoaoFMachado** [comment] 2018-03-23 16:36
Try to make sure youre only running that code after onDeviceReady is triggered

**Comment by jefvonmuhlen** [comment] 2018-03-23 16:37
Isso mesmo. Esse código esta no onDeviceReady.

Att.

*Set Consultoria*
Jef Anderson von Muhlen Moura
Consultor de Tecnologia
jef@setconsultoria.com.br
Fone: (62) 99410-4906


Em sex, 23 de mar de 2018 às 13:36, JoaoFMachado <notifications@github.com>
escreveu:

**Comment by JoaoFMachado** [comment] 2018-03-23 17:19
I managed to reproduce your issue. 
Having had the plugin working and obtaining the token correctly in the past i can say with some certainty that this is likely a side effect of the recent March 20th update. 
This plugin has had some difficulty working since then.
Do read: #612

**Comment by jefvonmuhlen** [comment] 2018-03-23 17:22
Já tentei todas as informações contida nos documentários, mas não deu certo.

Att.

*Set Consultoria*
Jef Anderson von Muhlen Moura
Consultor de Tecnologia
jef@setconsultoria.com.br
Fone: (62) 99410-4906


Em sex, 23 de mar de 2018 às 14:19, JoaoFMachado <notifications@github.com>
escreveu:

**Comment by JoaoFMachado** [comment] 2018-03-26 14:14
Managed to fix the issue, reinstalled the plugin (version 0.1.25) removed the android folder and rebuilt the project

**Comment by kyo4311** [comment] 2018-04-03 04:31
can't getToken. same issues.

**Comment by FabrizioFarenga** [comment] 2018-04-04 23:26
In my case the build was not updating the string.xml file. Check if it has been updated with your key and your api id. If not, the after_prepare.js (located in /plugins/cordova-plugin-firebase/scripts/) is not finding the strings.xml. I had to update the line 51 to `stringsXml: ANDROID_DIR + '/app/src/main/res/values/strings.xml'`

**Comment by soumak77** [comment] 2018-05-02 16:57
closing as resolved

**Closed by soumak77** 2018-05-02 16:57 UTC
