### ISSUE TITLE
getToken return empty string

### ISSUE THREAD

**Issue by itroteam** [arnesson/cordova-plugin-firebase#201] opened 2017-03-05 11:28 UTC
Hi!
first of all thanks for this plugin!
the getToken method is returning an empty sting but the plugin is working fine with notifications. Also onTokenRefresh is not working (it is never fired).
So notifications are working but token methods are not working.
`Utilities.logOnScreen` simply print on device screen the message (only for my comfort)

Thank you in advance!

Cordova 6.4.0
IDE NetBeans 8.2
OS: Xubuntu 16.04

Tested on Virtual Devices:
- android 4.0.3
- android 6.0
Tested on Real device:
- Huawuei P8 lite android 6.0

`
onDeviceReady: function () {
	this.receivedEvent('deviceready');

	window.FirebasePlugin.onTokenRefresh(function (token) {
	    Utilities.logOnScreen('onTokenRefresh ' + token);
	}, function (error) {
	    Utilities.logOnScreen('onTokenRefresh: ' + error);
	});

	jQuery("#getToken").click(function () {
	    window.FirebasePlugin.getToken(function (token) {
		Utilities.logOnScreen('getToken ' + token);
		console.log("token: " + token);
	    }, function (error) {
		Utilities.logOnScreen('getToken error: ' + error);
	    });
	});

	window.FirebasePlugin.onNotificationOpen(function (notification) {
	    Utilities.logOnScreen('wasTapped ' + JSON.stringify(notification));
	}, function (error) {
	    Utilities.logOnScreen('else ' + JSON.stringify(error));

	});

    }
`

**Comment by shepax** [comment] 2017-03-07 16:35
I did have the same problem,

mi solution was to fix the config.xml of the proyect changing the name of the `<widget id="same proyect name at firebase">`, rm the platform and validate that the google-services.json was not empty at the platform/android/

**Comment by VesperDev** [comment] 2017-03-15 05:13
@shepax Hi, I did not understand your answer, you can put the code fragment where the change is made. Thank you very much for your help

**Comment by VesperDev** [comment] 2017-03-15 06:00
This was the solution

Download your Firebase configuration files, GoogleService-Info.plist for ios and google-services.json for android, and place them in the root folder of your cordova project:

- My Project/
    platforms/
    plugins/
    www/
    config.xml
    **google-services.json       <--
    GoogleService-Info.plist   <--**

I need to add those two files to the project and with that they return the tokens correctly

**Comment by mdumrauf** [comment] 2017-03-28 11:19
I am still having this issue. Updating google-services.json didn't work. @robertarnesson ?

**Comment by shepax** [comment] 2017-04-07 13:09
@VesperDev  sorry for the bad exp,

When you build a project at firebase you have to define the iOS bundle ID or Android bundle ID, that bundle have to be the same that you have defined at the config.xml  of the ionic or cordoba project
`<widget id="bundle id">`

**Comment by Nerdcode** [comment] 2017-04-19 07:42
Still had the issue . please help

**Comment by Nerdcode** [comment] 2017-04-19 07:44
Hi,
I have the same issue. I placed the fcm config file in root folder and my widget id is same.
still  its getting empty token.

**Comment by juankysmith** [comment] 2017-04-20 13:33
I am having the same issue, yesterday I was receiving the token correctly but today I am getting empty string.  maybe the server is down because it is not possible to access to my project in firebase console

**Comment by BenjaminWatts** [comment] 2017-11-08 11:53
anyone fix this? I have exactly same problem - and the bundle id and package name I have in Firebase is definitely equal to the value of widget id!

**Comment by Noble-Shiva** [comment] 2018-01-28 18:08
Same Problem!

Need a fix urgently

**Comment by adadgio** [comment] 2018-02-22 15:39
The problem is still there... any update on this issue !?

**Comment by adadgio** [comment] 2018-02-22 16:03
Another solution is here: https://github.com/arnesson/cordova-plugin-firebase/issues/558

To the author: A PR and a fix is **URGENT** now... ;-)

**Comment by robertarnesson** [comment] 2018-02-26 17:56
closing this for now. the more recent problems are not related. see #558 for android 7 issues

**Closed by robertarnesson** 2018-02-26 17:56 UTC
