### ISSUE TITLE
device token getting null or blank in 0.1.23

### ISSUE THREAD

**Issue by priyasuthar** [arnesson/cordova-plugin-firebase#398] opened 2017-08-19 10:37 UTC
Hello team,

We are not getting token in latest version of fcm 0.1.23. My cordova cli version is 6.4.0, android cordova version is 6.0.0 and iOS cordova version is 4.3.1. Some time we get a null or blank ('') token. We are getting response in success function.

Let us know if any solution u have find.

Thanks in advance.

**Comment by myleshk** [comment] 2017-08-31 06:31
I'm getting null/'' all the time for android.

**Comment by illya13** [comment] 2017-09-06 12:03
have the same with 0.1.24

**Comment by illya13** [comment] 2017-09-06 12:04
the problem is in 0-size file  `platforms/android/google-services.json`

**Comment by sascha1337** [comment] 2017-09-06 14:13
got the same problem, getToken() returns NULL,
had the problem with existing google-services.json in /platforms/android/
ive deleted the file, re-added the plugin with cordova 
-> the `platforms/android/google-services.json` was a 0-size file 

but the problem is it does not work either. file exists, no luck, what now ?

**Comment by illya13** [comment] 2017-09-06 14:14
no luck yet

**Comment by illya13** [comment] 2017-09-06 14:52
checking diff
https://github.com/arnesson/cordova-plugin-firebase/compare/174b57d19f54f7155b6dcecb64cd62b5ef4dc731...f55513959eaa1425e18021adb404aa7c516e458f

**Comment by illya13** [comment] 2017-09-06 16:20
can you please report:
- os
- node / npm version 
- maybe full `ionic info`

The issue seems in updating of 
`platforms/android/res/values/strings.xml`

**Comment by illya13** [comment] 2017-09-06 17:25
again, current code has an issue in updating
`platforms/android/res/values/strings.xml`

**Comment by sascha1337** [comment] 2017-09-06 23:37
thank you for your info, cordova plugins add from newest github version works fine !

**Comment by illya13** [comment] 2017-09-07 13:09
@sascha1337 you mean from master ?
as `0.1.24` is not working for me

**Comment by rikbauwens** [comment] 2017-09-08 06:35
@illya13
I've had exactly the same issue. I fixed it by adding the following manually to my build.gradle file:

```
apply plugin: 'com.google.gms.google-services'
buildscript {
    ...
    dependencies {
        ...
        classpath 'com.google.gms:google-services:3.0.0'
    }
}

```
I also put the following lines in comment in the strings.xml file:

```
<!--<string name="google_app_id">@string/google_app_id</string>
    <string name="google_api_key">@string/google_api_key</string>-->
```

The downside is that I manually need to make these changes after each update in order to get the plugin to work. Is there any idea on what's the cause of this issue? In the plugin source, there is a file named build-extra.gradle wit the line "apply plugin: 'com.google.gms.google-services'", but it seems to be ignored.

**Comment by Rajeshtechgeek** [comment] 2017-09-09 11:12
Change the below lines in the (platforms/android/res/values/strings.xml)strings.xml file:

<string name="google_app_id">@string/google_app_id</string>
    <string name="google_api_key">@string/google_api_key</string>
to:

<string name="google_app_id">your google ap id from google-services.json</string>
    <string name="google_api_key">your google api key from google-services.json</string>

**Comment by cobusk** [comment] 2017-09-12 13:07
Actually, this plugin is broken pretty badly. @Rajeshtechgeek is correct about the change in `strings.xml`, but the problem is that you can then **must** build the app using Android Studio. If you use the Cordova CLI (which I want as part of my automatic release process), the plugin will add the original two lines back and you won't be able to build at all. So the plugin adds invalid gunk in there.

I fixed this by replacinging the two lines @Rajeshtechgeek mentioned, swappping

```
<string name="google_app_id">@string/google_app_id</string>
<string name="google_api_key">@string/google_api_key</string>
```

for 

```
<string name="google_app_id">your google app id from google-services.json</string>
<string name="google_api_key">your google api key from google-services.json</string>
```

And then, for the deep surgery...

1. In both `plugins/cordova-plugin-firebase/scripts` and `node_modules/cordova-plugin-firebase/scripts`, remove or comment out the entire contents of the `updateStringsXml` function in `after_prepare.js`. The documentation actually states that the hook script doesn't work for Phonegap builds, but they simply don't work at all.
2. In 'plugin.xml' (also in both `node_modules` and `plugins`, remove or comment out the `config-file` blocks for `google_app_id` and `google_api_key`. 

And build as usual. 

I know, I know. I should fork and make these changes. I simply don't have the time. 

I've had so much drama with the various FCM plugins, when I do have the time, I just may write my own from scratch.

**Comment by tryadelion** [comment] 2017-09-22 06:46
any news on this?

**Comment by ChrisBardsley** [comment] 2017-09-24 05:22
For anyone else who is having this issue, I found a much simpler solution. Im not positive if this is the right way to go about this or not but hopefully, it will be of help to someone else.

@cobusk comment pointed me to this, but as I was implementing his solution, it dawned on me, that all you really need to do is to modify the string.xml file to include your google key and id. Then when you do a build, it will naturally copy over the values.

DETAILS:
file: plugins/cordova-plugin-firebase/plugin.xml

change:
<string name="google_app_id">{Your app id here}</string>
<string name="google_api_key">{Your api key here}</string>

**Comment by ValentinKlinghammer** [comment] 2017-09-29 07:35
Are you all sure you are exactly on version `0.1.23` and not something like `^0.1.23`? Because the last one actually fetches `0.1.24` at the time of writing and that is the version that causes the empty string token on Android for our apps. `0.1.23` works fine across 3 of our apps in production.

**Comment by jskidd3** [comment] 2017-10-14 15:25
@ValentinKlinghammer Literally 3 hours of pulling my hair out finally led to your comment. Can absolutely clarify 0.1.23 pulls the correct app id and key into strings.xml. **Don't use 0.1.24 if you are trying to use the plugin on Android**.

**Comment by explofish** [comment] 2017-10-25 18:32
@ValentinKlinghammer Youre right! I confirm!

**Comment by dawDEV** [comment] 2017-10-27 13:27
Instructions to fix it in your downloaded code:
Open /plugins/cordova-plugin-firebase/scripts/after_prepare.js

Find the following code part:
```
// Copy key files to their platform specific folders
if (directoryExists(IOS_DIR)) {
    copyKey(PLATFORM.IOS);
} else if (directoryExists(ANDROID_DIR)) {
    copyKey(PLATFORM.ANDROID, updateStringsXml)
}
```

You can now already see the flaw, change it to:
```
// Copy key files to their platform specific folders
if (directoryExists(IOS_DIR)) {
    copyKey(PLATFORM.IOS);
}
if (directoryExists(ANDROID_DIR)) {
    copyKey(PLATFORM.ANDROID, updateStringsXml)
}
```

This should hotfix it until a new version is being deployed as it's already fixed in the current repo's state.

**Comment by CarlosFJ** [comment] 2017-11-23 08:59
Install plugin AngularFire, add AngularFireModule with the config to the Firebase project and set after_prepare.js in line 55. It's workin' now. Thank's!

**Comment by adadgio** [comment] 2018-02-22 16:02
Another solution is here: https://github.com/arnesson/cordova-plugin-firebase/issues/558

To the author: A PR and a fix is **URGENT** now... ;-)

**Closed** 2018-02-27 10:42 UTC

**Comment by fdambrosio** [comment] 2018-04-12 21:50
a fix is urgent , thanks

**Comment by Ubaid-Gul** [comment] 2019-02-12 05:54
What worked for me is.
I download google-services.json file again and replaced in the project.

- ionic-angular 3.9.2
- @ionic/app-scripts : 3.2.1

In platforms\android\project.properties file
- com.google.firebase:firebase-core:12.0.0
- com.google.firebase:firebase-messaging:12.0.0
- if required com.google.android.gms:play-services-location:12.0.0
  
In platforms\android\cordova-plugin-fcm-with-dependecy-updated\addexplorer-FCMPlugin.gradle file
`buildscript {
    repositories {
        mavenCentral()
        jcenter()
        mavenLocal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'
        classpath 'com.google.gms:google-services:4.0.2'
    }
}
repositories {
    mavenCentral()
    jcenter()
}
dependencies {
    compile 'com.google.firebase:firebase-core:12.0.0'
}
apply plugin: com.google.gms.googleservices.GoogleServicesPlugin`

In platforms\android\cordova-support-google-services\addexplorer-build.gradle

`buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'
        classpath 'com.google.gms:google-services:4.0.2'
    }
}
ext.postBuildExtras = {
    apply plugin: com.google.gms.googleservices.GoogleServicesPlugin
}`
