### ISSUE TITLE
Error on second build

### ISSUE THREAD

**Issue by ramzed** [arnesson/cordova-plugin-firebase#9] opened 2016-06-29 20:33 UTC
Hello,
Thank you for this project and your great job!

I have problem in ionic project.
First, I add the string in my config.xml:
```<plugin name="cordova-plugin-firebase" spec="https://github.com/arnesson/cordova-plugin-firebase" />```
Second, I put **google-services.json** (which I got from firebase web console) in root directory.
I run my build, and this works:
```
$ cordova run android
Running command: /home/user/android-app/App/hooks/after_prepare/010_add_platform_class.js /home/user/android-app/App
add to body class: platform-android
**Discovered plugin "cordova-plugin-firebase" in config.xml. Adding it to the project**
Fetching plugin "https://github.com/arnesson/cordova-plugin-firebase" via git clone
Repository "https://github.com/arnesson/cordova-plugin-firebase" checked out to git ref "master".
Installing "cordova-plugin-firebase" for android
ANDROID_HOME=/home/user/Android/Sdk/
JAVA_HOME=/opt/java/jdk1.8.0_92
No target specified, deploying to device 'F9AZCY31J032'.
:preBuild UP-TO-DATE
```

But my second build always fails...
```
$ cordova run android
Running command: /home/user/android-app/App/hooks/after_prepare/010_add_platform_class.js /home/user/android-app/App
add to body class: platform-android
Error: Invalid data, chunk must be a string or buffer, not object
```
I was trying to install plugin by ```cordova plugin add https://github.com/arnesson/cordova-plugin-firebase.git --save```. But in this case even first build crashes with ```Error: Invalid data, chunk must be a string or buffer, not object```

And when I start android application with first build, code below doesn't work for me:
```
angular.module('app', ['ionic', 'app.controllers', 'app.routes', 'app.services', 'app.directives', 'firebase'])

.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if (window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
      cordova.plugins.Keyboard.disableScroll(true);
    }
    if (window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleDefault();
    }

    window.FirebasePlugin.getInstanceId(function(token) {
      // save this server-side and use it to push notifications to this device
      console.log("Token", token);
    }, function(error) {
      console.error(error);
    });

  });
})
```
This code returns ["Token", "null"] to console.

Thank you in advance.

**Comment by robertarnesson** [comment] 2016-06-29 20:47
do you get any dupes or strange values in platforms/andoid/res/values/strings.xml?

try running cordova prepare android before building (although it should work without it)

**Comment by raducostea** [comment] 2016-06-30 09:41
Same issue here. In strings.xml i have:
```

    <string name="google_app_id">727247059290</string>
    <string name="google_app_id">@string/google_app_id</string>
    <string name="google_api_key">@string/google_api_key</string>
```

**Comment by dhruv270** [comment] 2016-06-30 11:17
Remove `google_app_id` from string.xml and try again. I have removed and it is working for me.

**Comment by raducostea** [comment] 2016-06-30 11:48
How about ios? do you have any idea?

**Comment by dhruv270** [comment] 2016-06-30 12:05
Nope. I don't have any idea for iOS. I think you need to add GoogleService-Info.plist file in iOS project and install Pod.
For you, is it started working in Android now?

**Comment by raducostea** [comment] 2016-06-30 14:49
Nope, i am getting Error: invalid data when i try to emulate it. I guess that the cordova prepare hook is changing the file back.

**Comment by dhruv270** [comment] 2016-07-01 06:33
@raducostea - I suggest you to use APN (Apple Push Notification). Here is the link of plugin: https://github.com/phonegap-build/PushPlugin. It is working very accurately for me in iOS.

**Comment by raducostea** [comment] 2016-07-01 07:57
@dhruv270 i am already using that. I want this plugin for the analytics part to record events and add them inside google analytics.

**Comment by neosekar** [comment] 2016-07-01 10:39
**Error: Invalid data** appeared because of the **google-services.json** and **googleService-info.plist** copy to platforms folder , if the platforms folder and json, plist doesn't exist it shows error.
I fixed by adding the platforms folder and json , plist file. Sorry for my bad english

**Comment by dhruv270** [comment] 2016-07-01 12:28
Yes, you need to create project at firebase console. And add application in that project by adding your application package name / bundle id. You will get google-services.json for Android and GoogleService-Info.plist for iOS. That file you need to add in your project.

**Comment by robertarnesson** [comment] 2016-07-01 15:26
make sure you put the files in the ROOT of your project, alongside config.xml etc, not in e.g. platforms or www.

@raducostea @dhruv270 Regarding APN and push, I would suggest using this plugin for that as well. PushPlugin will eventually switch to Firebase FCM as well (since GCM is deprecated). FCM uses APN for IOS so its the same thing, but you get the benefit of a common interface across all platforms

**Comment by raducostea** [comment] 2016-07-01 15:58
Already did that but i am getting compilation errors. Check https://github.com/arnesson/cordova-plugin-firebase/issues/11

**Comment by ramzed** [comment] 2016-07-01 21:12
I don't have any dupes or strange values in strings.xml.
I reinstalled cordova-plugin-firebase and made "cordova prepare". After that I was seeing new values in strings.xml:
```
<string name="google_app_id">@string/google_app_id</string>
<string name="google_api_key">@string/google_api_key</string>
```
And when I build the same error again:
Error: Invalid data, chunk must be a string or buffer, not object

**Comment by neosekar** [comment] 2016-07-02 05:30
Are you added both ios and android platform ?

**Comment by neosekar** [comment] 2016-07-02 05:35
Once I build android , i got this error

**UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/FirebaseException;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)


 FAILED**

**Comment by robinbonnes** [comment] 2016-07-05 16:35
I have the same issue as @neosekar . Any ideas?

**Comment by robertarnesson** [comment] 2016-07-06 21:34
Regarding Multiple dex files define Lcom/google/firebase/FirebaseException:

This is caused by duplicate dependencies, most likely another plugin which is also using the Firebase SDK or parts of it. I have not tested this myself but you should be able to list all dependencies used in your project and find the duplicates: 
http://stackoverflow.com/questions/30648172/gradle-library-duplicates-in-dependencies

**Comment by st8st8** [comment] 2016-08-19 13:30
Having a GoogleService-Info.plist when there's no ios platform will cause the "second build error".  I'd recommend  GoogleService-Info.plist is copied only if platform/ios exists....

You can patch after_prepare.js to work around this, though I've not tested my patch yet.  I'll post it if it works

**Comment by c4software** [comment] 2016-08-19 14:56
@st8st8 The problem is already fixed (on the git version)

```
...
if(fileExists("GoogleService-Info.plist") && directoryExists("platforms/ios/")){
...
```

**Closed** 2016-08-23 21:11 UTC

**Comment by thetomester13** [comment] 2017-01-26 17:28
I came across the same issue just now and after a while just redownloaded both the GoogleService-Info.plist and google-services.json files and it worked just fine.

**Comment by didinj** [comment] 2017-02-27 01:54
I facing the same issue with ionic. I fix that by remove platform and plugin then add again platform and plugin, then everything is completely normal again. 
For this issue in ionic 2 I write this [tutorial](https://www.djamware.com/post/58a1378480aca7386754130a/ionic-2-fcm-push-notification).

**Comment by tresdev** [comment] 2017-12-20 01:15
Reinstalling cordova-plugin-firebase worked for me
