### ISSUE TITLE
Android heads-up (peek notifications)

### ISSUE THREAD

**Issue by alexcroox** [arnesson/cordova-plugin-firebase#472] opened 2017-11-03 10:02 UTC
I have push notifications successfully arriving on my phone, however they don't "popup" when staring at my homescreen (with the app minimised), they just hide inside the pull down notification menu, and show an icon in the status bar.

Is there a configuration I'm missing that allows the notifications to slide down when they come in?

This is my code:

```
onDeviceReady: function() {

  window.FirebasePlugin.onTokenRefresh(function(token) {

      window.FirebasePlugin.subscribe("general-alerts");
  })
}
```

I'm sending messages from Firebase console with high priority and to an individual device using it's token.

**Comment by jozzhart** [comment] 2017-11-17 09:15
Hi @alexcroox this sounds like expected behaviour.  What OS are you on?  What do you mean "popup"?

**Comment by jozzhart** [comment] 2017-11-17 09:15
Hi @alexcroox this sounds like expected behaviour. What do you mean "popup"?

**Comment by alexcroox** [comment] 2017-11-24 08:33
@jozzhart like this, I think on Android they are called "peek" notifications?

![ss](https://cl.ly/nv76/Screenshot_20171123-160343_thumb.png)

**Comment by jozzhart** [comment] 2017-11-25 03:47
I see.  Sounds like a feature request.  I'm sure the maintainers would happily take a pull request.  Further details:

https://developer.android.com/guide/topics/ui/notifiers/notifications.html#Heads-up
https://firebase.google.com/docs/reference/admin/node/admin.messaging.MessagingOptions

**Comment by jozzhart** [comment] 2017-11-29 20:24
@alexcroox It looks to be an Android setting issue..   Once floating notifications are enabled for your app, it will work fine. 

![screenshot_2017-11-26-13-18-12-973_com android settings](https://user-images.githubusercontent.com/662502/33397150-dfee06aa-d59e-11e7-8d98-b20842359e3f.png)

![screenshot_2017-11-30-07-19-32-623_com android chrome](https://user-images.githubusercontent.com/662502/33397284-51bd3b98-d59f-11e7-9e41-ad81a91342e2.png)

**Comment by soumak77** [comment] 2018-05-10 06:50
fixed via https://github.com/arnesson/cordova-plugin-firebase/pull/684

**Closed by soumak77** 2018-05-10 06:50 UTC
Labels: android, enhancement, notifications

**Comment by aikei** [comment] 2018-05-11 05:14
I thought my pull request fixes this in all circumstances, but it appears it only fixes this for a situation where your app is running. Otherwise, it is OS task to show push notification in which case it won't popup, because of default priority. I now don't think we can do anything about this, what other apps like WhatsApp usually do, they use tricks to restart the app or a service after it is killed. Which I believe is outside of the scope of this plugin.
Correct me if I'm wrong.
